version: "3"
volumes:
  myvolume:
services:
  sw-app:
    container_name: sw-container
    depends_on:
      - mysqldb
    image: sw-app
    build: .
    ports:
      - 9090:8080
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-mysqldb}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
      ENV: ${ENV:-dev}
      SECRET: ${SECRET:-secret}

  mysqldb:
    container_name: mysqldb
    image: mysql
    cap_add:
      - SYS_NICE
    volumes:
      -  myvolume:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-api}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}